// <auto-generated />
using System;
using FYP_25_S3_15P.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FYP_25_S3_15P.Migrations
{
    [DbContext(typeof(SmartDbContext))]
    [Migration("20251017182557_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FYP_25_S3_15P.Models.ApplicationForm", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppId"));

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("ApplicantName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Notes");

                    b.Property<int>("PlanID")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.Property<int>("UniId")
                        .HasColumnType("int")
                        .HasColumnName("UniID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("AppId");

                    b.HasIndex("PlanID");

                    b.HasIndex("UniId");

                    b.ToTable("ApplicationForm", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Assessment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("FYPTopicID")
                        .HasColumnType("int");

                    b.Property<int>("GroupID")
                        .HasColumnType("int")
                        .HasColumnName("GroupID");

                    b.Property<int?>("MarkAwarded")
                        .HasColumnType("int")
                        .HasColumnName("MarkAwarded");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SubmittedAt");

                    b.HasKey("ID");

                    b.HasIndex("FYPTopicID");

                    b.HasIndex("GroupID");

                    b.ToTable("Assessments", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CourseCode");

                    b.Property<string>("CourseID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CourseID");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CourseName");

                    b.Property<int?>("ModuleID")
                        .HasColumnType("int");

                    b.Property<string>("ProgramID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProgramID");

                    b.Property<int?>("UniversityProgramID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("ModuleID");

                    b.HasIndex("ProgramID");

                    b.HasIndex("UniversityProgramID");

                    b.ToTable("Courses", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FAQs", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.FYPTemplates", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FYPTopicID")
                        .HasColumnType("int");

                    b.Property<string>("ProgramID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UniID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("FYPTopicID");

                    b.HasIndex("ProgramID");

                    b.HasIndex("UniID");

                    b.ToTable("FYPTemplates", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.FYPTopic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ProgramID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Program_Abbrev_Year_Session_IndexNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SessionID")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TopicDesc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TopicTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UniversityID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProgramID");

                    b.HasIndex("SessionID");

                    b.HasIndex("UniversityID");

                    b.ToTable("FYPTopics", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Feature", b =>
                {
                    b.Property<int>("FeatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HomeOrder")
                        .HasColumnType("int");

                    b.Property<string>("HomeSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowOnHome")
                        .HasColumnType("bit");

                    b.HasKey("FeatureID");

                    b.ToTable("Features", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.GlobalUniConstraint", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ALoadCap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ALoadCap");

                    b.Property<string>("PTeamSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PTeamSize");

                    b.Property<string>("PrefRankLimit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PrefRankLimit");

                    b.Property<string>("SLoadCap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SLoadCap");

                    b.Property<int>("UniID")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("UniID");

                    b.HasKey("ID");

                    b.HasIndex("UniID");

                    b.ToTable("GlobalUniConstraints", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Group", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsFullTime")
                        .HasColumnType("bit");

                    b.Property<int>("TopicID")
                        .HasColumnType("int");

                    b.Property<int?>("UniversityID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("TopicID");

                    b.HasIndex("UniversityID");

                    b.ToTable("Groups", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Module", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CourseID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CourseID");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ModuleCode");

                    b.Property<string>("ModuleID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ModuleID");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ModuleName");

                    b.HasKey("ID");

                    b.HasIndex("CourseID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("Modules", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.PlanFeature", b =>
                {
                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.Property<int>("FeatureID")
                        .HasColumnType("int");

                    b.HasKey("PlanID", "FeatureID");

                    b.HasIndex("FeatureID");

                    b.ToTable("PlanFeatures", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Preference", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Rank");

                    b.Property<string>("TopicID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FYPTopics");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ID");

                    b.HasIndex("TopicID");

                    b.HasIndex("UserID");

                    b.ToTable("Preferences", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Programs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProgramCode");

                    b.Property<string>("ProgramID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProgramID");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProgramName");

                    b.Property<string>("UniID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UniID");

                    b.Property<int?>("UniversityID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("CourseID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("UniID");

                    b.HasIndex("UniversityID");

                    b.ToTable("Programs", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Session", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Dte_fr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Dte_fr");

                    b.Property<string>("Dte_to")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Dte_to");

                    b.Property<string>("SessionNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SessionNo");

                    b.Property<string>("UniID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UniID");

                    b.Property<int?>("UniversityID")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Year");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("UniID");

                    b.HasIndex("UniversityID");

                    b.ToTable("Sessions", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.StaffModule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ModuleID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ModuleID");

                    b.Property<int>("StaffID")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.HasKey("ID");

                    b.HasIndex("ModuleID");

                    b.HasIndex("StaffID");

                    b.ToTable("StaffModules", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.StaffProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("StaffID")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("StaffProfiles", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.StudentModules", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModuleID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("ModuleID");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentModules", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.StudentProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CourseID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CourseID");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PhoneNo");

                    b.Property<int>("SessionID")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("SessionID");

                    b.Property<int>("StudentID")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int>("UserID")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<bool>("isFullTime")
                        .HasColumnType("bit")
                        .HasColumnName("isFullTime");

                    b.HasKey("ID");

                    b.HasAlternateKey("StudentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("SessionID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("StudentProfiles", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlanID");

                    b.ToTable("subscriptionPlans", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.TaskEvaluation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CriterionLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CriterionLabel");

                    b.Property<double>("DeliverableScore")
                        .HasColumnType("float")
                        .HasColumnName("DeliverableScore");

                    b.Property<double>("FinalContribution")
                        .HasColumnType("float")
                        .HasColumnName("FinalContribution");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SAvedAt");

                    b.Property<double>("Score")
                        .HasColumnType("float")
                        .HasColumnName("Score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("Weight");

                    b.Property<double>("Weighted")
                        .HasColumnType("float")
                        .HasColumnName("Weighted");

                    b.HasKey("ID");

                    b.HasIndex("TaskID");

                    b.ToTable("TaskEvaluations", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Tasks", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DueAt");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FileName");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SubmittedAt");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SubmittedBy");

                    b.Property<string>("TaskDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TaskDesc");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TaskTitle");

                    b.HasKey("ID");

                    b.HasIndex("GroupID");

                    b.ToTable("Tasks", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.UniSession", b =>
                {
                    b.Property<int>("UniID")
                        .HasColumnType("int")
                        .HasColumnName("UniID");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.Property<int>("SessionID")
                        .HasColumnType("int")
                        .HasColumnName("SessionID");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_Frm");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_To");

                    b.HasKey("UniID", "Year", "SessionID");

                    b.HasIndex("SessionID");

                    b.ToTable("UniSession", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.University", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("UniID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UniID");

                    b.Property<string>("UniName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UniName");

                    b.Property<string>("UnivCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UnivCode");

                    b.HasKey("ID");

                    b.HasIndex("UniID")
                        .IsUnique();

                    b.ToTable("Universities", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.UniversityProgram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgramID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UniID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UniID");

                    b.ToTable("Program", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailDomain")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailNormalized")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsersID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EmailNormalized")
                        .IsUnique()
                        .HasFilter("[EmailNormalized] IS NOT NULL");

                    b.HasIndex("RoleID");

                    b.HasIndex("UniID");

                    b.HasIndex("UsersID");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.UserGroups", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("GroupID")
                        .HasColumnType("int");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GroupID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserGroups", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.UserRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoles", "dbo");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.ApplicationForm", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.University", "University")
                        .WithMany("ApplicationForms")
                        .HasForeignKey("UniId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("University");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Assessment", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.FYPTopic", null)
                        .WithMany("Assessments")
                        .HasForeignKey("FYPTopicID");

                    b.HasOne("FYP_25_S3_15P.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Course", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleID");

                    b.HasOne("FYP_25_S3_15P.Models.Programs", "Programs")
                        .WithMany()
                        .HasForeignKey("ProgramID")
                        .HasPrincipalKey("ProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.UniversityProgram", null)
                        .WithMany("Courses")
                        .HasForeignKey("UniversityProgramID");

                    b.Navigation("Module");

                    b.Navigation("Programs");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.FYPTemplates", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.FYPTopic", null)
                        .WithMany("FYPTemplates")
                        .HasForeignKey("FYPTopicID");

                    b.HasOne("FYP_25_S3_15P.Models.Programs", "Programs")
                        .WithMany()
                        .HasForeignKey("ProgramID")
                        .HasPrincipalKey("ProgramID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniID")
                        .HasPrincipalKey("UniID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Programs");

                    b.Navigation("University");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.FYPTopic", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Programs", "Programs")
                        .WithMany()
                        .HasForeignKey("ProgramID")
                        .HasPrincipalKey("ProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID");

                    b.HasOne("FYP_25_S3_15P.Models.University", "University")
                        .WithMany("FYPTopics")
                        .HasForeignKey("UniversityID");

                    b.Navigation("Programs");

                    b.Navigation("Session");

                    b.Navigation("University");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.GlobalUniConstraint", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Group", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.FYPTopic", "FYPTopic")
                        .WithMany()
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.University", null)
                        .WithMany("Groups")
                        .HasForeignKey("UniversityID");

                    b.Navigation("FYPTopic");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Module", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .HasPrincipalKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.PlanFeature", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Feature", "Feature")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("FeatureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.SubscriptionPlan", "Plan")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("PlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Preference", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.FYPTopic", "FYPTopic")
                        .WithMany()
                        .HasForeignKey("TopicID")
                        .HasPrincipalKey("TopicID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FYPTopic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Programs", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID");

                    b.HasOne("FYP_25_S3_15P.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniID")
                        .HasPrincipalKey("UniID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.University", null)
                        .WithMany("Programs")
                        .HasForeignKey("UniversityID");

                    b.Navigation("Course");

                    b.Navigation("University");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Session", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniID")
                        .HasPrincipalKey("UniID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.University", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UniversityID");

                    b.Navigation("University");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.StaffModule", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleID")
                        .HasPrincipalKey("ModuleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.StaffProfile", "StaffProfile")
                        .WithMany("StaffModules")
                        .HasForeignKey("StaffID")
                        .HasPrincipalKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.StaffProfile", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.User", "User")
                        .WithOne("StaffProfile")
                        .HasForeignKey("FYP_25_S3_15P.Models.StaffProfile", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.StudentModules", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleID")
                        .HasPrincipalKey("ModuleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.StudentProfile", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .HasPrincipalKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("FYP_25_S3_15P.Models.StudentProfile", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.TaskEvaluation", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Tasks", "Task")
                        .WithMany()
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Tasks", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.UniSession", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("University");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.UniversityProgram", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.User", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniID")
                        .HasPrincipalKey("UniID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FYP_25_S3_15P.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("UsersID");

                    b.Navigation("Role");

                    b.Navigation("University");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.UserGroups", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FYP_25_S3_15P.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID");

                    b.HasOne("FYP_25_S3_15P.Models.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.UserRole", b =>
                {
                    b.HasOne("FYP_25_S3_15P.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FYP_25_S3_15P.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.FYPTopic", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("FYPTemplates");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Feature", b =>
                {
                    b.Navigation("PlanFeatures");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Group", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.Role", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.StaffProfile", b =>
                {
                    b.Navigation("StaffModules");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("PlanFeatures");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.University", b =>
                {
                    b.Navigation("ApplicationForms");

                    b.Navigation("FYPTopics");

                    b.Navigation("Groups");

                    b.Navigation("Programs");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.UniversityProgram", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("FYP_25_S3_15P.Models.User", b =>
                {
                    b.Navigation("Preferences");

                    b.Navigation("StaffProfile");

                    b.Navigation("StudentProfile");

                    b.Navigation("UserGroups");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
